### ISSUE TITLE
Thank you + Docker version

### ISSUE THREAD

**Issue by joopdo** [linucksrox/exifsort#2]
I'm using your script succesfully since 2017. My new environment does not support Perl, so I made a docker version:
https://github.com/joopdo/docker-exifsort

Thank you for your perl script!!

**Comment by linucksrox** [comment]
@joopdo Hey, thanks for commenting! I'm glad this is helpful to you. For a long time I had planned on adding better support for all the different date tags but never got around to it. Maybe I will do that sometime soon.

Thanks for packaging this into Docker, I think that's a much better way to run this stuff especially because I remember it being a pain to get perl and dependencies installed.
